package PFiches;

import java.io.IOException; //Pour gérer les erreurs de fichier
import javax.swing.JOptionPane; //Pour afficher des messages
import projetvtc.Passager; //pour gérer des utilisateurs

public class FPassagerEspace extends javax.swing.JDialog {

    private Passager Passager; //pour stocker la passager connecté ou inscrit

    public FPassagerEspace(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Passager = null; //On initialise le passager
    }

    public void initPass(Passager P) { //Pour récupérer le passager qui se connecte ou s'inscrit
        Passager = P;
        lMsg.setText("Bienvenue " + Passager.getNom() + "."); //message personnalisé de bienvenue
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lMsg = new javax.swing.JLabel();
        bDeconnexion = new javax.swing.JButton();
        bCommander = new javax.swing.JButton();
        bAnciennesCommandes = new javax.swing.JButton();
        bProfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lMsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        bDeconnexion.setText("se déconnecter");
        bDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeconnexionActionPerformed(evt);
            }
        });

        bCommander.setText("Commander");
        bCommander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCommanderActionPerformed(evt);
            }
        });

        bAnciennesCommandes.setText("Voir les anciennes commande");
        bAnciennesCommandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnciennesCommandesActionPerformed(evt);
            }
        });

        bProfil.setText("Modifier le profil");
        bProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bDeconnexion)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAnciennesCommandes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bProfil))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bCommander))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(bCommander)
                .addGap(18, 18, 18)
                .addComponent(bAnciennesCommandes)
                .addGap(18, 18, 18)
                .addComponent(bProfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(bDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeconnexionActionPerformed
        Passager = null; //on efface de cette page le passager qui se déconnecte
        this.setVisible(false); //On rend invisible cette page puis on affiche la page de connexion
        ((Accueil) getParent()).getFicheC().setVisible(true);
    }//GEN-LAST:event_bDeconnexionActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            (((Accueil) getParent()).getSite()).sauvegarde(); //On sauvegarde toutes les infos en gérant les possibles erreurs
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur inconnue de sauvegarde.");
        } finally {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosed

    private void bProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProfilActionPerformed
        (((Accueil) this.getParent()).getFicheProfilPass()).setVisible(true); //on affiche la page du profil du passager puis on rend invisible la page où on se trouve
        this.setVisible(false);
    }//GEN-LAST:event_bProfilActionPerformed

    private void bCommanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCommanderActionPerformed
        (((Accueil) getParent()).getFicheCommande()).setVisible(true); //on affiche la page de commande puis on rend invisible la page où on se trouve
        this.setVisible(false);
    }//GEN-LAST:event_bCommanderActionPerformed

    private void bAnciennesCommandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnciennesCommandesActionPerformed
        (((Accueil) getParent()).getFicheEspaceCommande()).setVisible(true); //on affiche la page des anciennes commandes du passager puis on rend invisible la page où on se trouve
        this.setVisible(false);
    }//GEN-LAST:event_bAnciennesCommandesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPassagerEspace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPassagerEspace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPassagerEspace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPassagerEspace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FPassagerEspace dialog = new FPassagerEspace(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnciennesCommandes;
    private javax.swing.JButton bCommander;
    private javax.swing.JButton bDeconnexion;
    private javax.swing.JButton bProfil;
    private javax.swing.JLabel lMsg;
    // End of variables declaration//GEN-END:variables
}
