package PFiches;

import java.io.IOException; //Pour gérer les erreurs de fichier
import javax.swing.JOptionPane; //Pour afficher des messages
import projetvtc.ExMdpFaux; //Pour gérer différents types d'erreurs
import projetvtc.ExVide;
import projetvtc.Passager; //Pour gérer des passagers

public class FProfilPass extends javax.swing.JDialog {

    private Passager P; //Pour stocker le passager utilisant cette page
    private String nom; //pour stocker ses infos
    private String mail;
    private String tel;
    private String mdp;
    private boolean cb;

    public FProfilPass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void initPass(Passager Pass) { //Pour récupérer le passager utilisant cette page
        P = Pass;
        nom = P.getNom(); //on récupère ses infos
        mail = P.getMail();
        tel = P.getNbtel();
        mdp = P.getMdp();
        cb = P.isCB();
        tfNom.setText(nom); //on attribut ses infos aux composants correspondnats
        tfMail.setText(mail);
        tfTel.setText(tel);
        pfMdp.setText(mdp);
        pfMdp2.setText(mdp);
        if (cbCB.isSelected()) { //S'il paye en carte bleue
            cbCB.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRetour = new javax.swing.JButton();
        lNom = new javax.swing.JLabel();
        lMail = new javax.swing.JLabel();
        lTel = new javax.swing.JLabel();
        lMdp = new javax.swing.JLabel();
        lCB = new javax.swing.JLabel();
        cbCB = new javax.swing.JCheckBox();
        pfMdp = new javax.swing.JPasswordField();
        tfNom = new javax.swing.JTextField();
        tfMail = new javax.swing.JTextField();
        bValider = new javax.swing.JButton();
        lEspace = new javax.swing.JLabel();
        lMdp2 = new javax.swing.JLabel();
        pfMdp2 = new javax.swing.JPasswordField();
        tfTel = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        lNom.setText("Nom:");

        lMail.setText("Mail:");

        lTel.setText("Téléphone:");

        lMdp.setText("Mot de passe:");

        lCB.setText("Payez-vous en carte bleu:");

        cbCB.setText("Oui");

        bValider.setText("Valider");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        lEspace.setText("Bienvenue sur votre profil.");

        lMdp2.setText("Confirmez votre mot de passe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(bValider))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(lEspace, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lCB)
                    .addComponent(lMdp2)
                    .addComponent(lMdp)
                    .addComponent(lTel)
                    .addComponent(lMail)
                    .addComponent(lNom))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(tfMail)
                    .addComponent(pfMdp)
                    .addComponent(cbCB)
                    .addComponent(pfMdp2)
                    .addComponent(tfTel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lEspace)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNom)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMail)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTel)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMdp)
                    .addComponent(pfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMdp2)
                    .addComponent(pfMdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCB)
                    .addComponent(cbCB))
                .addGap(31, 31, 31)
                .addComponent(bValider)
                .addGap(20, 20, 20)
                .addComponent(bRetour)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        this.setVisible(false); //On rend invisible cette page et on affiche la page précédente
        ((Accueil) getParent()).getFicheP().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        try {
            String mdp1, mdp2; //Variables pour contenir les mot de passes
            String nom, mail, tel; //Variables pour contenir les infos sur le passager
            mdp1 = String.valueOf(pfMdp.getPassword()); //On récupère les mot de passes et on les convertit en texte
            mdp2 = String.valueOf(pfMdp2.getPassword());
            nom = tfNom.getText(); //on récupère les autres infos entrées
            mail = tfMail.getText();
            tel = tfTel.getText(); 
            Integer.valueOf(tel); //Pour vérifier si le tel est composé de chiffres sinon ca propage une erreur
            if (!mdp1.equals(mdp2)) { //Si les deux mots de passes ne sont pas identiques
                throw new ExMdpFaux();
            }
            if (nom.equals("") || mdp1.equals("") || mail.equals("") || tel.equals("")) { //Si un ou plusieurs champs sont vides
                throw new ExVide();
            }
            cb = cbCB.isSelected(); //on regarde si le passager paye en carte bleue
            P.modifierInfos(cb, nom, mail, mdp1, tel); //on modifie ses infos
            JOptionPane.showMessageDialog(this, "Votre profil de passager a bien été modifié."); //message de confirmation
            (((Accueil) this.getParent()).getFicheP()).setVisible(true); //on affiche la page de l'espace passager
            this.setVisible(false); //On rend invisible cette page
        } catch (ExMdpFaux ex) { //Si les deux mots de passes ne sont pas identiques
            JOptionPane.showMessageDialog(this, "Vos mots de passe ne sont pas identiques.");
        } catch (NumberFormatException ex) { //Si l'utilisateur n'a pas etré que des chiffres pour le téléphone
            JOptionPane.showMessageDialog(this, "Veuillez entrer seulement des chiffres pour le téléphone.");
        } catch (ExVide ex) { //Si un ou plusieurs champs sont vides
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs..");
        } catch (Exception ex) { //S'il ya une erreur inconnue
            JOptionPane.showMessageDialog(this, "Erreur incconue!");
        }
    }//GEN-LAST:event_bValiderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            (((Accueil) getParent()).getSite()).sauvegarde(); //On sauvegarde toutes les infos en gérant les possibles erreurs
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur inconnue de sauvegarde.");
        } finally {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProfilPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProfilPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProfilPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProfilPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FProfilPass dialog = new FProfilPass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRetour;
    private javax.swing.JButton bValider;
    private javax.swing.JCheckBox cbCB;
    private javax.swing.JLabel lCB;
    private javax.swing.JLabel lEspace;
    private javax.swing.JLabel lMail;
    private javax.swing.JLabel lMdp;
    private javax.swing.JLabel lMdp2;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lTel;
    private javax.swing.JPasswordField pfMdp;
    private javax.swing.JPasswordField pfMdp2;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfNom;
    private javax.swing.JFormattedTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
