package PFiches;

import java.io.IOException; //Pour gérer les erreurs de fichier
import javax.swing.JOptionPane; //Pour afficher des messages
import projetvtc.Conducteur; //Pour gérer des conducteurs
import projetvtc.ExVide; //pour gérer des erreurs particulières
import projetvtc.Vehicule; //Pour gérer des véhicules

public class FProfilCond extends javax.swing.JDialog {

    private Conducteur C; //pour stocker le conducteur utilisant cette page
    private String nom; //variables pour stocker ses infos
    private String mail;
    private String permis; //Le type de permis
    private String tel;
    private String mdp;
    private Vehicule typeVehic; //Le type de véhicule du conducteur
    private int cartegrise; //Le numéro de carte grise du conducteur

    public FProfilCond(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void initCond(Conducteur cond) { //Pour récupérer le conducteur qui va utiliser cette page
        C = cond;
        typeVehic = C.getTypeVehic(); //on affecte toutes ses infos aux variables servant à cela
        nom = C.getNom();
        mail = C.getMail();
        permis = C.getPermis();
        tel = C.getNbtel();
        cartegrise = C.getCartegrise();
        mdp = C.getMdp();
        tfNom.setText(nom); //on affiche ses infos dans les composants correspondants
        tfMail.setText(mail);
        tfCarteGrise.setText("" + cartegrise);
        tfTel.setText(tel);
        tfMdp.setText(mdp);
        if (permis.equals("B")) { //S'il a le permis voiture
            rbPermisB.setSelected(true);
        } else if (permis.equals("moto")) { //S'il a le permis moto
            rbPermisMoto.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTypeVehic = new javax.swing.ButtonGroup();
        lNom = new javax.swing.JLabel();
        lMail = new javax.swing.JLabel();
        lTel = new javax.swing.JLabel();
        tfNom = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        tfCarteGrise = new javax.swing.JTextField();
        lBienvenue = new javax.swing.JLabel();
        lPermis = new javax.swing.JLabel();
        lCarteGrise = new javax.swing.JLabel();
        lMdp = new javax.swing.JLabel();
        tfMdp = new javax.swing.JPasswordField();
        tfMail = new javax.swing.JTextField();
        bValider = new javax.swing.JButton();
        bRetour = new javax.swing.JButton();
        rbPermisB = new javax.swing.JRadioButton();
        rbPermisMoto = new javax.swing.JRadioButton();
        bModifVehic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lNom.setText("Nom:");

        lMail.setText("Adresse mail:");

        lTel.setText("Numéro de tel:");

        lBienvenue.setText("Bienvenue sur votre profil.");

        lPermis.setText("Type de permis:");

        lCarteGrise.setText("Numéro de carte grise:");

        lMdp.setText("Mot de passe:");

        bValider.setText("Valider les changements");
        bValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderActionPerformed(evt);
            }
        });

        bRetour.setText("Retour");
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });

        bgTypeVehic.add(rbPermisB);
        rbPermisB.setText("Voiture");
        rbPermisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPermisBActionPerformed(evt);
            }
        });

        bgTypeVehic.add(rbPermisMoto);
        rbPermisMoto.setText("Moto");
        rbPermisMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPermisMotoActionPerformed(evt);
            }
        });

        bModifVehic.setText("Modifier le véhicule");
        bModifVehic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifVehicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lMdp)
                    .addComponent(lMail)
                    .addComponent(lTel)
                    .addComponent(lNom)
                    .addComponent(lPermis)
                    .addComponent(lCarteGrise))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPermisMoto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbPermisB)
                    .addComponent(tfCarteGrise, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bRetour)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bValider)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bModifVehic)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNom)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTel)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPermis)
                    .addComponent(rbPermisB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPermisMoto)
                .addGap(16, 16, 16)
                .addComponent(bModifVehic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCarteGrise)
                    .addComponent(tfCarteGrise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMdp)
                    .addComponent(tfMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bValider)
                .addGap(24, 24, 24)
                .addComponent(bRetour)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        this.setVisible(false); //on rend invisible cette page puis on affiche la page précédente
        ((Accueil) getParent()).getFicheCond().setVisible(true);
    }//GEN-LAST:event_bRetourActionPerformed

    private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderActionPerformed
        try {
            //Si un ou plusieurs champs sont vides
            if ((tfCarteGrise.getText().equals("")) || (tfNom.getText().equals("")) || (tfMail.getText().equals("")) || (tfTel.getText().equals("")) || (tfMdp.getText().equals(""))) {
                throw new ExVide();
            }
            cartegrise = Integer.valueOf(tfCarteGrise.getText()); //On récupère son numéro de carte grise et on le convertit en int
            nom = tfNom.getText(); //On récupère ses autres infos dans les composants correspondants
            mail = tfMail.getText();
            tel = tfTel.getText();
            Integer.valueOf(tel); //Pour vérifier si le tel est composé de chiffres sinon ca propage une erreur
            mdp = String.valueOf(tfMdp.getPassword()); //On récupère son nouveau mot de passe et on le convertit en texte
            C.modifierInfos(permis, cartegrise, nom, mail, mdp, tel); //on envoie toutes ses nouvelles infos pour que la fonction les modifie
            JOptionPane.showMessageDialog(this, "Vos modifications ont été enregistrées."); //message de confirmation
        } catch (ExVide ex) { //Si un ou plusieurs champs sont vides
            JOptionPane.showMessageDialog(this, "Tous les champs n'ont pas été remplis.");
        } catch (NumberFormatException ex) { //Si l'utilisateur n'a pas etré que des chiffres pour le téléphone
            JOptionPane.showMessageDialog(this, "Veuillez entrer seulement des chiffres pour le téléphone.");
        }
    }//GEN-LAST:event_bValiderActionPerformed

    private void rbPermisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPermisBActionPerformed
        //Quand l'utilisateur choisie le permis voiture
        permis = "B";
    }//GEN-LAST:event_rbPermisBActionPerformed

    private void rbPermisMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPermisMotoActionPerformed
        //Quand l'utilisateur choisie le permis moto
        permis = "moto";
    }//GEN-LAST:event_rbPermisMotoActionPerformed

    private void bModifVehicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifVehicActionPerformed
        this.setVisible(false); //On rend invisible cette page puis on affiche la page pour modifier son véhicule
        ((Accueil) getParent()).getFicheVehic().setVisible(true);
        ((Accueil) getParent()).getFicheVehic().initCond(C); //on envoie les infos du conducteurs à la page
    }//GEN-LAST:event_bModifVehicActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            (((Accueil) getParent()).getSite()).sauvegarde(); //On sauvegarde toutes les infos en gérant les possibles erreurs
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur inconnue de sauvegarde.");
        } finally {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProfilCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProfilCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProfilCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProfilCond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FProfilCond dialog = new FProfilCond(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModifVehic;
    private javax.swing.JButton bRetour;
    private javax.swing.JButton bValider;
    private javax.swing.ButtonGroup bgTypeVehic;
    private javax.swing.JLabel lBienvenue;
    private javax.swing.JLabel lCarteGrise;
    private javax.swing.JLabel lMail;
    private javax.swing.JLabel lMdp;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lPermis;
    private javax.swing.JLabel lTel;
    private javax.swing.JRadioButton rbPermisB;
    private javax.swing.JRadioButton rbPermisMoto;
    private javax.swing.JTextField tfCarteGrise;
    private javax.swing.JTextField tfMail;
    private javax.swing.JPasswordField tfMdp;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
}
